name: Build Docker Images

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: oceanic
        password: $DOCKER_HUB_TOKEN
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.0.2
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.1.2
    - name: Build the Docker images
      run: make build
